apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: roboshop-ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1 
kind: Pod
metadata: 
  name: nginx
  labels: 
    purpose: ebs-dynamic
    project: roboshop
spec: 
  nodeSelector:
    #disktype: ssd #change with topolgy
  containers:
  - name: nginx
    image: nginx 
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic
---
apiVersion: v1 
kind: Service
metadata: 
  name: ebs-dynamic
  labels: 
    purpose: ebs-dynamic
    project: roboshop
spec: 
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
    project: roboshop
  ports:
  - protocol: TCP
    port: 80 #service port
    targetport: 80 #container port