apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop-spot-ng
    instanceTypes: 
      - c7i-flex.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    spot: true


 # spot-cluster.yaml

# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: roboshop
#   region: us-east-1

# managedNodeGroups:
# - name: roboshop
#   instanceTypes: [ t3.large ]
#   desiredCapacity: 2
#   spot: true